### ISSUE TITLE
Make a readme

### ISSUE THREAD

**Issue by macsj200** [PCHSTechClub/Krypton#1]
Sup PCHS, I'm curious what you guys are doing lately. Y'all should make a readme for your projects.

**Comment by Darokrithia** [comment]
Will do.  Btw do you want to come in some time

I have a few finished games and other stuff not solely on github.

**Comment by macsj200** [comment]
I'm in California unfortunately, but I'll definitely try to drop by when I'm back in town.

**Comment by Darokrithia** [comment]
Sweet.  Read me should be done this afternoon.  Also, how is berkley?
